fine_tuning_subjects:
  ${datasets[0]}:
    - UTS08

fine_tune_disjoint: false

train_cfg:
  batch_size: 2
  lr: 0.00001
  lr_decoder: ${fine_tune_cfg.train_cfg.lr}
  weight_decay: 0.001
  weight_decay_decoder: ${fine_tune_cfg.train_cfg.weight_decay}