[tool.poetry]
name = "decoding"
version = "0.1.0"
description = ""
authors = ["Louis Jalouzot <louis.jalouzot@ens-lyon.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"
torch = "^2.3.0"
joblib = "^1.4.2"
numpy = "^1.26.4"
clip = {git = "https://github.com/openai/CLIP.git"}
ftfy = "^6.2.0"
regex = "^2024.4.28"
tqdm = "^4.66.2"
setuptools = "^69.5.1"
scikit-learn = "^1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
