[tool.poetry]
name = "decoding"
version = "0.1.0"
description = ""
authors = ["Louis Jalouzot <louis.jalouzot@ens-lyon.fr>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"
torch = "^2.2.0"
joblib = "^1.4.2"
numpy = "^1.26.4"
clip = {git = "https://github.com/openai/CLIP.git"}
ftfy = "^6.2.0"
regex = "^2024.4.28"
setuptools = "^69.5.1"
scikit-learn = "^1.4.2"
wandb = "^0.17.0"
h5py = "^3.11.0"
transformers = "^4.41.1"
skorch = "^1.0.0"
torchmetrics = "^1.4.0.post0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
