defaults:
  - _self_
  - splitting: train_test
  - decoder_cfg: brain_decoder
  - fine_tune_cfg: none
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

meta: # Ignored for caching and wandb id
  cache: false
  log_wandb: false
  wandb_project: fMRI-Decoding-wrap-up
  wandb_mode: online
  tags: []
  return_data: false

seed: 0
return_tables: false
log_nlp_distances: false
n_candidates: 10

datasets: lebel2023
subjects: null
runs: null

tr: 2
alignment_cfg:
  lag: 3
  smooth: 0
  stack: 0

top_encoding_voxels: 3000

latents_cfg:
  context_length: 3
  model: bert-base-uncased
  token_aggregation: mean

train_cfg:
  monitor: valid/relative_rank_median
  patience: 20
  scheduler_patience: 5
  batch_size: 1
  max_epochs: 200

wrapper_cfg:
  loss: mixco
  multi_subject_mode: individual
  temperature: 0.05
  temperature_ft: 0.5
  beta: 0.15
  s_thresh: 0.5
  lr: ${decoder_cfg.lr}
  lr_ft: ${decoder_cfg.lr_ft}
  weight_decay: ${decoder_cfg.weight_decay}
  weight_decay_ft: ${decoder_cfg.weight_decay_ft}
  hidden_dim: ${decoder_cfg.hidden_dim}
  dropout: ${decoder_cfg.dropout}
  norm_type: ${decoder_cfg.norm_type}
  activation_layer_first: ${decoder_cfg.activation_layer_first}