defaults:
  - _self_
  - splitting: train_test
  - decoder_cfg: brain_decoder
  - fine_tune_cfg: none
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom

meta:
  cache: false
  log_wandb: false
  wandb_project: fMRI-Decoding-wrap-up
  wandb_mode: online
  tags: []
  return_data: false

seed: 0
return_tables: false
log_nlp_distances: false
n_candidates: 10
performance_ceiling: false

datasets: lebel2023_fmriprep
subjects: null
runs: null

tr: 2
alignment_cfg:
  lag: 3
  smooth: 4
  stack: 0

top_encoding_voxels: 4096

latents_cfg:
  context_length: 3
  model: intfloat/multilingual-e5-large
  token_aggregation: mean

train_cfg:
  monitor: valid/mean_reciprocal_rank
  direction: higher_is_better # or lower_is_better
  patience: 20
  scheduler_patience: 5
  batch_size: 1
  batch_size_ft: 3
  max_epochs: 200

wrapper_cfg:
  loss: symm_nce
  multi_subject_mode: individual
  temperature: 0.7
  temperature_ft: 1
  beta: 0.005
  beta_ft: ${wrapper_cfg.beta}
  s_thresh: 0.05
  s_thresh_ft: ${wrapper_cfg.s_thresh}
  lr: 0.0001
  lr_ft: 0.00001
  weight_decay: 0.0005
  weight_decay_ft: 0.005
  hidden_dim: 2048
  dropout: 0.5
  norm_type: "ln" # @param ["ln", "bn"]
  activation_layer_first: false

hydra:
  run:
    dir: outputs/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: ""