defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep
subjects:
  lebel2023_fmriprep:
    - UTS02
    - UTS03

train_cfg:
  monitor: valid/mse

wrapper_cfg:
  loss: mse

splitting:
  train_ratio: 0.46

meta:
  tags: [overlap,classical]

hydra:
  sweeper:
    params:
      wrapper_cfg.multi_subject_mode: individual,shared
      top_encoding_voxels: 768,null
      ++splitting.overlap: 0,1,0.5,0.25,0.75