defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep

meta:
  tags: [subject_4_small]

top_encoding_voxels: 8192

wrapper_cfg:
  hidden_dim: 128

hydra:
  sweeper:
    params:
      +subjects.lebel2023_fmriprep: UTS04,[UTS01,UTS02,UTS03,UTS04]