defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep

splitting:
  n_folds: 15
  train_ratio: 0.3

meta:
  tags: [overlap_v4]

hydra:
  launcher:
    cpus_per_task: 72
  sweeper:
    params:
      wrapper_cfg.hidden_dim: 64,4096
      splitting.overlap: 0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1
      +subjects.lebel2023_fmriprep: UTS01,UTS02,UTS03,[UTS01,UTS02,UTS03]