defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep_balanced

meta:
  tags: [single_subject,lebel2023_fmriprep_balanced]

hydra:
  sweeper:
    params:
      ++subjects.lebel2023_fmriprep_balanced: UTS01,UTS02,UTS03,UTS04,UTS05,UTS06,UTS07,UTS08