defaults:
  - slurm_JZ
  - _self_

datasets: lebel2023_fmriprep_balanced
subjects:
  lebel2023_fmriprep_balanced: UTS01

meta:
  tags: [baseline_v2]

hydra:
  sweeper:
    params:
      +baseline: random,performance_ceiling