defaults:
  - experiments
  - _self_

meta:
  tags: [multi_subject]

hydra:
  launcher:
    cpus_per_task: 10
    mem_gb: 100
  sweeper:
    params:
      wrapper_cfg.multi_subject_mode: shared,individual
      datasets: lebel2023_balanced,lebel2023_fmriprep_balanced