defaults:
  - experiments
  - _self_

meta:
  tags: [increase_data,mean_subject]

hydra:
  sweeper:
    params:
      datasets: lebel2023_fmriprep_mean,lebel2023_fmriprep_123_mean
      splitting.train_ratio: 0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,null