defaults:
  - experiments
  - _self_

subjects:
  lebel2023_fmriprep: UTS03

hydra:
  sweeper:
    params:
      latents_cfg.model: Alignment-Lab-AI/e5-mistral-7b-instruct,intfloat/multilingual-e5-large