defaults:
  - experiment_compare_approach
  - _self_

meta:
  tags: [fine_tune]

hydra:
  launcher:
    cpus_per_task: 5
    mem_gb: 50
  sweeper:
    params:
      ++dataset: lebel2023_balanced
      ++subjects.lebel2023_balanced: UTS01,UTS02,UTS03,UTS04,UTS05,UTS06,UTS07,UTS08