defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep
subjects: lebel_fmriprep_123

splitting:
  n_folds: 15

meta:
  tags: [setup_v3]

hydra:
  sweeper:
    params:
      latents_cfg.context_length: 0,3
      alignment_cfg.lag: 0,3
      alignment_cfg.smooth: 0,4
      latents_cfg.model: bert-base-uncased,McGill-NLP/LLM2Vec-Meta-Llama-31-8B-Instruct-mntp-unsup-simcse
      decoder_cfg: simple_mlp,brain_decoder
      wrapper_cfg.loss: mse,symm_nce