defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep

meta:
  tags: [increase_data_v2]

hydra:
  sweeper:
    params:
      +subjects.lebel2023_fmriprep: UTS04,UTS05,UTS06,UTS07,UTS08
      splitting.train_ratio: 0,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,null