defaults:
  - experiments
  - _self_

datasets: lebel2023_fmriprep

meta:
  tags: [subj_data_dim_overlap_123]

hydra:
  sweeper:
    params:
      # Testing
      # +subjects.lebel2023_fmriprep: [UTS01,UTS02,UTS03]
      # wrapper_cfg.hidden_dim: 8192
      # splitting.train_ratio: 0.9
      # splitting.overlap: 1

      +subjects.lebel2023_fmriprep: UTS01,UTS02,UTS03,[UTS01,UTS02],[UTS01,UTS03],[UTS02,UTS03],[UTS01,UTS02,UTS03]
      wrapper_cfg.hidden_dim: 512,1024,2048,4096,8192
      splitting.train_ratio: 0.1,0.3,0.5,0.7,0.9
      splitting.overlap: 0,0.25,0.5,0.75,1