defaults:
  - _self_
  - config
  - override splitting: cv
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: moead

hydra:
  # launcher:
  #   submitit_folder: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/.submitit/%j
  #   timeout_min: 60
  #   cpus_per_task: 5
  #   gpus_per_node: 1
  #   mem_gb: 10
  #   name: ${hydra.job.name}
  #   partition: gpu
  #   stderr_to_stdout: true
  mode: MULTIRUN
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.id}
  sweeper:
    sampler:
      seed: 0
      population_size: 50  # MOEAD specific parameter
      cross_over_probability: 0.9  # MOEAD specific parameter
      mutation_probability: 0.1  # MOEAD specific parameter
      # weight_vector_type can be 'random' or 'normal-boundary'
      weight_vector_type: 'random' # @param ['random', 'normal-boundary']
    direction: minimize
    study_name: moead_search
    n_trials: 1
    n_jobs: 2
    params:
      hidden_dim: