defaults:
  - _self_
  - multirun
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/%j
    timeout_min: 2880
    cpus_per_task: 20
    gpus_per_node: 1
    mem_gb: 100
    name: ${hydra.job.name}
    partition: gpu
    stderr_to_stdout: true