class: BrainDecoder
hidden_dim: 768
hidden_dim_projector: 768
dropout: 0.5
n_res_blocks: 1
n_proj_blocks: 1
norm_type: "ln" # @param ["ln", "bn"]
activation_layer_first: False
lr: 0.0001
lr_ft: 0.00001
weight_decay: 0.0005
weight_decay_ft: 0.005